baseURL = "https://bachdx2812.github.io"
languageCode = "en-us"
title = "Bachdx's"
theme = "sam"
pygmentsStyle = "monokai"
pygmentsCodefences = true

[[params.mainMenu]]
    link = "/gallery"
    text = "Photos"

[[params.mainMenu]]
    link = "/posts"
    text = "Stuff"

[[params.mainMenu]]
    link = "/about"
    text = "Bachdx Who?"

